version : '3'
services :
  postgres :
    image : "postgres:13.13"
    container_name : kvcrm-dev-backend-postgres
    restart : unless-stopped
    ports :
      - "5432:5432"
    environment :
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=svc_testing_db
  redis:
    image: "redis:alpine"
    restart: always
    container_name: kvcrm-dev-backend-redis
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
  prometheus :
    container_name : kvcrm-dev-backend-prometheus
    image : prom/prometheus:v2.48.1
    volumes :
      - ./src/main/docker/prometheus/:/etc/prometheus/
    command :
      - '--config.file=/etc/prometheus/prometheus.yml'
    # On MacOS, remove next line and replace localhost by host.docker.internal in src/main/docker/prometheus/prometheus.yml and
    # docker/grafana/provisioning/datasources/datasource.yml
    network_mode : 'host' # to test locally running service
  grafana :
    container_name : kvcrm-dev-backend-grafana
    image : grafana/grafana:10.2.2
    volumes :
      - ./src/main/docker/grafana/provisioning/:/etc/grafana/provisioning/
    environment :
      - GF_SECURITY_ADMIN_PASSWORD=changeme
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    # On MacOS, remove next line and replace localhost by host.docker.internal in src/main/docker/prometheus/prometheus.yml and
    # docker/grafana/provisioning/datasources/datasource.yml
    network_mode : 'host' # to test locally running service
